### ISSUE TITLE
JAR file not working

### ISSUE THREAD

**Issue by andrewscw** [troomtroom/duke#7]
@troomtroom  All your iP peer reviewers reported that they could not get the JAR file to work. I tried it myself and it did not seem to work:

This is what is displayed when I run the JAR file, with presumably an error message :

![image](https://user-images.githubusercontent.com/39245054/67147316-7e6c8b80-f2c6-11e9-9238-a8867c9bea6d.png)
 
This means we are unable to grade your iP.
Please release a new version that is cross-platform and confirmed to work with Java 11. 
In addition, if the JAR file released is not your latest version, please update it as well. 

Also, do update your User Guide so that your implementations and functionalities are reflected with clear instructions and examples on how a user can test them. 
When it is ready, post here to let me know ASAP (deadline: a week from today).

**Comment by KartikeKhandelwal** [comment]
The deadline is Sunday midnight, right?

**Comment by andrewscw** [comment]
Yes, if possible do submit earlier for us to evaluate

**Comment by KartikeKhandelwal** [comment]
The Website is updated and the jar file problem is also fixed now. It runs across Linux and Windows with a java -jar command.
